---
name: mypy

"on":
  push:
    branches:
      - main
  pull_request:

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
      - name: Running type checks
        run: |
          uv --no-config sync --locked --dev
          uv run ty check
